#![allow(nonstandard_style)]

#[derive(Debug)]
pub enum JavaScriptKeyword {
    break_,
    case,
    catch,
    class,
    const_,
    default,
    delete,
    do_,
    else_,
    export,
    extends,
    false_,
    function,
    if_,
    import,
    in_,
    new,
    null,
    return_,
    switch,
    this,
    throw,
    true_,
    try_,
    as_,
    interface,
    let_,
    type_,
    undefined,
}

#[derive(Debug)]
pub enum SkibidiScriptKeyword {
    scram,
    cook,
    findOut,
    iykyk,
    levelTenGyat,
    slay,
    exile,
    bruh,
    riddleMeThat,
    beGone,
    inflateMaxx,
    cap,
    skibidi,
    riddleMeThis,
    summon,
    plugged,
    crisp,
    brokeBehavior,
    hesDoneFor,
    letHim,
    that,
    throwItBack,
    noCap,
    fuckAround,
    twinn,
    squad,
    levelOneGyat,
    aura,
    wentOutToBuyCigarettes,
}

pub const KEYWORDS: [(JavaScriptKeyword, SkibidiScriptKeyword); 29] = [
    (JavaScriptKeyword::break_, SkibidiScriptKeyword::scram),
    (JavaScriptKeyword::case, SkibidiScriptKeyword::cook),
    (JavaScriptKeyword::catch, SkibidiScriptKeyword::findOut),
    (JavaScriptKeyword::class, SkibidiScriptKeyword::iykyk),
    (
        JavaScriptKeyword::const_,
        SkibidiScriptKeyword::levelTenGyat,
    ),
    (JavaScriptKeyword::default, SkibidiScriptKeyword::slay),
    (JavaScriptKeyword::delete, SkibidiScriptKeyword::exile),
    (JavaScriptKeyword::do_, SkibidiScriptKeyword::bruh),
    (JavaScriptKeyword::else_, SkibidiScriptKeyword::riddleMeThat),
    (JavaScriptKeyword::export, SkibidiScriptKeyword::beGone),
    (
        JavaScriptKeyword::extends,
        SkibidiScriptKeyword::inflateMaxx,
    ),
    (JavaScriptKeyword::false_, SkibidiScriptKeyword::cap),
    (JavaScriptKeyword::function, SkibidiScriptKeyword::skibidi),
    (JavaScriptKeyword::if_, SkibidiScriptKeyword::riddleMeThis),
    (JavaScriptKeyword::import, SkibidiScriptKeyword::summon),
    (JavaScriptKeyword::in_, SkibidiScriptKeyword::plugged),
    (JavaScriptKeyword::new, SkibidiScriptKeyword::crisp),
    (JavaScriptKeyword::null, SkibidiScriptKeyword::brokeBehavior),
    (JavaScriptKeyword::return_, SkibidiScriptKeyword::hesDoneFor),
    (JavaScriptKeyword::switch, SkibidiScriptKeyword::letHim),
    (JavaScriptKeyword::this, SkibidiScriptKeyword::that),
    (JavaScriptKeyword::throw, SkibidiScriptKeyword::throwItBack),
    (JavaScriptKeyword::true_, SkibidiScriptKeyword::noCap),
    (JavaScriptKeyword::try_, SkibidiScriptKeyword::fuckAround),
    (JavaScriptKeyword::as_, SkibidiScriptKeyword::twinn),
    (JavaScriptKeyword::interface, SkibidiScriptKeyword::squad),
    (JavaScriptKeyword::let_, SkibidiScriptKeyword::levelOneGyat),
    (JavaScriptKeyword::type_, SkibidiScriptKeyword::aura),
    (
        JavaScriptKeyword::undefined,
        SkibidiScriptKeyword::wentOutToBuyCigarettes,
    ),
];
